server:
  port: 8081

spring:
  application:
    name: Mach33_URL_Validation
  data:
    mongodb:
      uri: mongodb+srv://jbarseneau:Cheech99@cluster0.rd3fpku.mongodb.net/url_validation
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

url-validation:
  connect-timeout-ms: 10000
  socket-timeout-ms: 20000
  max-redirects: 5
  concurrent-validations: 20
  user-agent: "SpaceDataArchive URL Validator/1.0" 