spring:
  application:
    name: mach33-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-discovery-dashboard
          uri: lb://service-discovery
          predicates:
            - Path=/dashboard.html
          filters:
            - RedirectTo=302, /eureka/dashboard.html
        - id: service-discovery
          uri: lb://service-discovery
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: google-search
          uri: lb://mach33-google-search
          predicates:
            - Path=/mach33-google-search/**
          filters:
            - RewritePath=/mach33-google-search/(?<remaining>.*), /${remaining}
        - id: catalog-processor
          uri: lb://mach33-catalog-processor
          predicates:
            - Path=/mach33-catalog-processor/**
          filters:
            - RewritePath=/mach33-catalog-processor/(?<remaining>.*), /${remaining}
        - id: url-validation
          uri: lb://mach33-url-validation
          predicates:
            - Path=/mach33-url-validation/**
          filters:
            - RewritePath=/mach33-url-validation/(?<remaining>.*), /${remaining}
        - id: llm-connection
          uri: lb://mach33-llm-connection
          predicates:
            - Path=/mach33-llm-connection/**
          filters:
            - RewritePath=/mach33-llm-connection/(?<remaining>.*), /${remaining}
        - id: nlp-service
          uri: lb://mach33-nlp-service
          predicates:
            - Path=/mach33-nlp-service/**
          filters:
            - RewritePath=/mach33-nlp-service/(?<remaining>.*), /${remaining}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080 