server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: url-validation-service
          uri: lb://url-validation-service
          predicates:
            - Path=/api/validation/**
          filters:
            - StripPrefix=1
        - id: catalog-processor-service
          uri: lb://catalog-processor-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=1
        - id: nlp-service
          uri: lb://nlp-service
          predicates:
            - Path=/api/nlp/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 