apiVersion: apps/v1
kind: Deployment
metadata:
  name: mach33-api-gateway
  labels:
    app: mach33-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mach33-api-gateway
  template:
    metadata:
      labels:
        app: mach33-api-gateway
    spec:
      containers:
      - name: mach33-api-gateway
        image: spacedataarchive/api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 