spring:
  application:
    name: MACH33-API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: eureka-server
          uri: lb://MACH33-EUREKA-SERVER
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
        - id: service-discovery-dashboard
          uri: http://service-discovery:8761
          predicates:
            - Path=/dashboard.html, /css/**, /js/**, /api/registry, /api/health, /images/**
        - id: service-template
          uri: lb://MACH33-SERVICE-TEMPLATE
          predicates:
            - Path=/api/template/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: templateCircuitBreaker
                fallbackUri: forward:/fallback/template

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.mach33: DEBUG
    org.springframework.cloud.gateway: DEBUG 