server:
  port: 8083

spring:
  application:
    name: url-validation
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 