apiVersion: apps/v1
kind: Deployment
metadata:
  name: mach33-nlp-service
  labels:
    app: mach33-nlp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mach33-nlp-service
  template:
    metadata:
      labels:
        app: mach33-nlp-service
    spec:
      containers:
      - name: mach33-nlp-service
        image: spacedataarchive/nlp-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: nlp-service-connection-string
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 