spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: website_catalog
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

logging:
  level:
    com.spacedataarchive: WARN
    org.springframework: WARN
  file:
    name: /var/log/website-catalog/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7 