spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb+srv://jbarseneau:Cheech99@cluster0.rd3fpku.mongodb.net/website-catalog
      database: website-catalog

server:
  port: ${PORT:0}  # Dynamic port assignment

port-manager:
  enabled: true
  range:
    min: 8081
    max: 8999

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    com.spacedataarchive: INFO
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG  # Added for MongoDB debugging 