apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual encoded values
  url-validation-connection-string: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L3VybF92YWxpZGF0aW9u
  nlp-service-connection-string: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L25scF9zZXJ2aWNl
  catalog-processor-connection-string: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L2NhdGFsb2dfcHJvY2Vzc29y 