server:
  port: 8761

spring:
  application:
    name: Mach33_Service_Discovery
  security:
    user:
      name: eureka
      password: password

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0 