name: Development CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Run Tests
      run: ./mvnw test

    - name: Build and Start Services
      run: |
        cd scripts
        ./start-microservices.sh -e dev

    - name: Build UI
      run: |
        cd ui
        npm install
        npm run build 