name: Production CI/CD

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    # Require approval before deploying to production
    environment:
      name: production
      url: https://your-production-url.com

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Run Tests
      run: ./mvnw test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose.production.yml build
        docker-compose -f docker-compose.production.yml push

    - name: Deploy to Production
      run: |
        docker-compose -f docker-compose.production.yml pull
        docker-compose -f docker-compose.production.yml up -d 