name: Staging CI/CD

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Run Tests
      run: ./mvnw test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose.staging.yml build
        docker-compose -f docker-compose.staging.yml push

    - name: Deploy to Staging
      run: |
        docker-compose -f docker-compose.staging.yml pull
        docker-compose -f docker-compose.staging.yml up -d 