name: Deploy Tree Navigation

on:
  push:
    branches: [ main ]
    paths:
      - 'adminHierarchy.json'
      - 'tree-nav.css'
      - 'tree-navigation.js'
      - 'tree-nav/**'
      - 'fix-admin-ui-path.sh'
      - 'enhance-tree-nav.sh'
      - '.github/workflows/tree-nav-deploy.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: Deploy enhanced tree navigation
      run: |
        # Make script executable
        chmod +x ./enhance-tree-nav.sh
        
        # Run the enhanced tree navigation script
        ./enhance-tree-nav.sh
        
        echo "Tree navigation deployment completed"
        
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        
        # Check if the ConfigMap exists
        if kubectl get configmap admin-ui-tree-nav -n mach33 &> /dev/null; then
          echo "✅ ConfigMap admin-ui-tree-nav exists"
        else
          echo "❌ ConfigMap admin-ui-tree-nav does not exist"
          exit 1
        fi
        
        # Check if admin-service pod is running
        ADMIN_POD=$(kubectl get pods -n mach33 -l app=admin-service -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
        if [ -n "$ADMIN_POD" ]; then
          POD_STATUS=$(kubectl get pod $ADMIN_POD -n mach33 -o jsonpath='{.status.phase}')
          if [ "$POD_STATUS" == "Running" ]; then
            echo "✅ admin-service pod is running"
          else
            echo "❌ admin-service pod status: $POD_STATUS"
            kubectl describe pod $ADMIN_POD -n mach33
            exit 1
          fi
        else
          echo "❌ admin-service pod not found"
          kubectl get pods -n mach33
          exit 1
        fi
        
        echo "Verification completed successfully"
        echo "The enhanced tree navigation has been deployed to production"

    - name: Post-deployment notification
      if: success()
      run: |
        echo "Tree navigation successfully deployed to production via GitHub Actions"
        echo "Timestamp: $(date)"
        # Add Slack or email notification here if needed 